### ISSUE TITLE
precision Watt critical loads

### ISSUE THREAD

**Issue by EmielWitteman** [victronenergy/dbus_modbustcp#19]
/opt/victronenergy/dbus-modbustcp/attributes.csv
Has a line:
`com.victronenergy.vebus,/Ac/Out/L1/P,i,VA or Watts,23,int16,0.1,R   `                                                                                                                                                                                                                                                                                                                                                                                                                          
Why the 0.1? This way I can only see the critical loads in tens of Watts
Ik hacked it to:
`com.victronenergy.vebus,/Ac/Out/L1/P,i,VA or Watts,23,int16,1,R`
Which gives the expected precision of a single Watt (no decimals)
Now I can read this value with homeassistant:
```
- name: victron                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  type: tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  host: x.x.x.x  # use the IP address of your CCGX                                                                                                                                                                                                                                                                                                                                                                                                                                     
  port: 502                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  sensors:                      
    - name: "Victron AC-out L1 power"                                                                                                                                                                                                                                                                                                                                                                                                                                                          
      scan_interval: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
      unit_of_measurement: "W"                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
      data_type: int16                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
      scale: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
      precision: 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
      slave: 228 #multiplus on vebus, check modbus services                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
      address: 23                  
```
